
services:
  web:
    build: .
    container_name: php_nube_grafiles
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MONGO_HOST=mongo-server  
    networks:
      - mongodb_network  


networks:
  mongodb_network:
    external: true 